obj-$(CONFIG_JZ_ONCHIP_HDMI) += \
speakerAllocationDataBlock.o \
shortAudioDesc.o \
halEdid.o \
videoCapabilityDataBlock.o \
monitorRangeLimits.o \
colorimetryDataBlock.o \
hdmivsdb.o \
edid.o \
dtd.o \
shortVideoDesc.o \
